apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-datalake-class-blob
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: pv-datalake-class-blob
  storageClassName: azureblob-fuse-premium