apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-blob-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azureblob-nfs
  resources:
    requests:
      storage: 100Gi
  volumeName: azure-blob-pv